In [14]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [15]:
print(l1)

[[3.34396236e-01 9.39236796e-01 1.01378446e-01 4.05025864e-01]
 [5.80734054e-03 3.01499202e-02 2.57029101e-04 9.72402056e-01]
 [8.11303431e-01 9.99961166e-01 9.14792024e-01 9.66029649e-01]
 [4.76096955e-02 9.81055663e-01 2.38819404e-02 9.99321062e-01]]


In [16]:
print(l2)

[[0.00202773]
 [0.99519492]
 [0.99669065]
 [0.00486455]]


In [17]:
print(syn1)

[[  4.95123659]
 [-11.80035623]
 [  8.60264142]
 [  5.81867107]]


In [18]:
print(syn0)

[[ 2.14687276  7.41808854  4.55560578  3.73227542]
 [-4.454445   -6.20904521 -6.08406738  3.94659858]
 [-0.6883688   2.73808322 -2.18200205 -0.38456718]]
